// Generated by https://quicktype.io

export class Jwt {
    jwt:        string;
    userAccess: string;

    constructor (
        jwt: string,
        userAccess: string,

      ) {
        this.jwt = jwt
        this.userAccess = userAccess
      }
}
