// Generated by https://quicktype.io

export class Jwt {
    jwtData: string;
    userAccess: string;

    constructor (
        jwtData: string,
        userAccess: string,

      ) {
        this.jwtData = jwtData
        this.userAccess = userAccess
      }
}
